name: Publish Dev

on:
  push:
    branches: [ "dev" ]

jobs:
  publish-pkg:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup build cache
        uses: actions/cache@v3.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish to Github Packages
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gradle-version: 7.3.3
          arguments: publish
